# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d525cbc8f3d60f94a2c74c3b7f4b6e1fde05c5bdd72c43321bdee47cf46d27219d87f6643648bcd24fa621665b7fb50ef068a226ef75f5a2e6e20e1985a2eac8

test:
  secret_key_base: cc82193593ae46b8c07bd329e2d5b86754371e51e0b5dbee20ba31ba8324d2794d7214ed3a297e22faf8bcfc9e0461ae7891c134016befc63aabe6317da6dfda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
